export const axiomFollowMap: Map<string, string> = new Map([
  ['ax-mp', '|- ps -| ph -| wi ps ph'],
  ['ax-1', '|- wi ph wi ps ph'],
  ['ax-2', '|- wi (wi ph wi ps ch) (wi (wi ph ps) (wi ph ch))'],
  ['ax-3', '|- wi (wi wn ph wn ps) (wi ps ph)'],
  ['df-bi', '|- wn wi (wi (wb ph ps) (wn wi wi ph ps wn wi ps ph)) wn wi (wn wi wi ph ps wn wi ps ph) (wb ph ps)'],
  ['df-an', '|- wb wa ph ps wn wi ph wn ps'],
  ['df-or', '|- wb wo ph ps wi wn ph ps'],
  ['df-ifp', '|- wb (wif ph ps ch) (wo wa ph ps wa wn ph ch)'],
  ['df-3or', '|- wb (w3o ph ps ch) (wo wo ph ps ch)'],
  ['df-3an', '|- wb (w3a ph ps ch) (wa wa ph ps ch'],
  ['df-nan', '|- wb (wnan ph ps) (wn wa ph ps)'],
  ['df-xor', '|- wb (wxo ph ps) (wn wb ph ps)'],
  ['df-tru', '|- wb T. wi (wal x wceq cv x cv x) (wal x wceq cv x cv x)'],
  ['df-fal', '|- wb F. wn T.'],
  ['df-had', '|- wb (whad ph ps ch) (wxor wxor ph ps ch)'],
  ['df-cad', '|- wb (wcad ph ps ch) (wo (wa ph ps) (wa ch wxor ph ps))'],
  ['df-ex', '|- wb wex x ph wn wal x wn ph'],
  ['df-nf', '|- wb wnf x ph wi wex x ph wal x ph'],
  ['ax-gen', '|- wal x ph -| ph'],
  ['ax-4', '|- wi (wal x wi ph ps) (wi wal x ph wal x ps)'],
  ['ax-5', '|- wi ph wal x ph'],
  ['ax-6', '|- wn wal x wn wceq cv x cv y'],
  ['ax-7', '|- wi (wceq cv x cv y) wi (wceq cv x cv z) (wceq cv y cv z)'],
  ['df-sb', '|- wb (wsb x t ph) (wal y (wi wceq cv y cv t wal x wi wceq cv x cv y ph))'],
  ['ax-8', '|- wi wceq cv x cv y wi wcel cv x cv z wcel cv y cv z'],
  ['ax-9', '|- wi wceq cv x cv y wi wcel cv z cv x wcel cv z cv y'],
  ['ax-10', '|- wi wn wal x ph wal x wn wal x ph'],
  ['ax-11', '|- wi wal x wal y ph wal y wal x ph'],
  ['ax-12', '|- wi wceq cv x cv y wi wal y ph wal x wi wceq cv x cv y ph'],
  ['ax-13', '|- wi wn wceq cv x cv y wi wceq cv y cv z wal x wceq cv y cv z'],
  ['df-mo', '|- wb wmo x ph wex y wal x wi ph wceq cv x cv y'],
  ['df-eu', '|- wb weu x ph wa wex x ph wmo x ph'],
]);
